### ISSUE TITLE
 All Android 13 roms using your vendor tree won't run Honor of Kings

### ISSUE THREAD

**Issue by limingerf** [nishant6342/vendor_realme_RMX3031#1]
All Android 13 roms using your vendor tree won't run Honor of Kings (com.tencent.tmgp.sgame)
08-17 17:17:15.367 31817 32160 E Escher-GameCore: ###   Escher call stacks   ###
08-17 17:17:15.367 31817 32160 E Escher-GameCore: # moduleName: Escher-GameCore #
08-17 17:17:15.367 31817 32160 E Escher-GameCore:
08-17 17:17:15.367 31817 32160 E Escher-GameCore: @ Csb/1/1093711-1.csb
08-17 17:17:15.367 31817 32160 E Escher-GameCore: @ /data/user/0/com.tencent.tmgp.sgame/files/TP/Csb/1/Data/1093711_1194038-1.csb
08-17 17:17:15.367 31817 32160 E Escher-il2cpp: ###   Escher call stacks   ###
08-17 17:17:15.367 31817 32160 E Escher-il2cpp: # moduleName: Escher-il2cpp #
08-17 17:17:15.367 31817 32160 E Escher-il2cpp:
08-17 17:17:15.367 31817 32160 E Escher-il2cpp: @ Csb/0/1093711-1.csb
08-17 17:17:15.367 31817 32160 E Escher-il2cpp: @ /data/user/0/com.tencent.tmgp.sgame/files/TP/Csb/0/Data/1093711_1194038-1.csb
08-17 17:17:15.367 31817 32160 E Escher-il2cpp: ## thread: 494281235632 ##
08-17 17:17:15.367 31817 32160 E Escher-il2cpp: Last Exception call stacks:
08-17 17:17:15.367 31817 32160 E Escher-il2cpp:         0x10(16) @330142

**Comment by nishant6342** [comment]
This app isn't available in playstore for india so i cant test , provide full crash log if app is crashing.

**Comment by BlueSwordM** [comment]
I just tried the app, and it doesn't even load.

Does it do any sort of check for the unlocked bootloader or something?
